### ISSUE TITLE
Truncate select-entities option

### ISSUE THREAD

**Issue by jegsen** [jweisman/eca-components#1]
Hi.
It would be nice to be able to truncate entities in the select-entities list. Maybe with some kind of property for setting truncation on/off and limit on component-level.

**Comment by jweisman** [comment]
Hi @jegsen - thanks for your suggestion. Is this what you had in mind?
![Screen Shot 2021-12-14 at 17 09 14 ](https://user-images.githubusercontent.com/80420/146025583-b1bd1732-fb5a-4c86-938b-28734b6c034a.png)

**Comment by jegsen** [comment]
Absolutely brilliant :1st_place_medal: The main focus was to limit entry-descriptions to one line in the cloud app.

**Comment by jweisman** [comment]
Great- we've released version [1.4.1](https://github.com/jweisman/eca-components/releases/tag/v1.4.1) which includes this and updated the [doc](https://github.com/jweisman/eca-components/blob/master/docs/select-entities.md). Hope this helps.

**Comment by jegsen** [comment]
Great work :-) 
Can you perhaps supply me with (a link to a) how to bring the new release in action for an existing project?
Thanks.

**Comment by jweisman** [comment]
Hi @jegsen - you can update the version in the package.json file, and then run `npm install`:
```
"eca-components": "^1.4.1",
```
